# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf5581bcd81335ff2dbe9a401b7c74db520a1c1d6e6c4cbf1561bd455e47c535f7fafacb14709c9162ad74b57a22889f55a21ca235f0c19a7b34c65e2650e92c

test:
  secret_key_base: 602bf7a7cf8942ac6d02d5f7375bb7e62c63d83025194e015dae36a3f6e19e01769546070718c71198f8acac0ae125759520ddd7ac592f9181518bc4c4475334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
